database:
    path: data/development
    path2: data/development2
dispatcher:
    cpfp_amount: 546
    cpfp_fee: 141
rpc:
    network: regtest
    url:  http://user:password@localhost:18443
    username: user
    password: password
    wallet: test_wallet
monitor:
    checkpoint_height: 10
key_manager:
    key_derivation_seed: deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
    key_derivation_path: m/101/1/0/0/
    winternitz_seed: deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
    storage:
        password: secret_password
        path: data/development/key_manager
